(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



// stage content:
(lib.Chapter1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhCC6QgTgFgNgIQgNgJgHgKQgGgMgBgLQAAgMAHgKQAGgLAMgJIAJAFIAIAGQgEAHgDAHQgCAHAAAGQAAALAFAIQAGAIAJAGQAKAFAOADQANADAQAAQAUAAASgFQARgFAMgJQAMgJAGgMQAGgMAAgOQAAgLgEgHQgFgHgHgEQgIgEgKgCQgKgBgMAAIgTAAIgWAAIgSABIgMAAQgPAAgLgEQgLgEgIgGQgIgHgDgJQgEgJAAgKQAAgOAHgOQAGgQAPgPQgLgMgHgPQgFgQAAgRQAAgSAGgRQAGgQANgMQAMgMASgHQASgIAXAAQAUAAARAHQAQAGAMAKQAHgIAHgFQAIgFAGgCQAGgDAFgBIAKgBQAHAAAFACQAFACADADIAEAIIABAIQAAAIgEAHQgGAHgKAAQgIAAgHgFQgHgFgCgKQgGACgEADIgKAHQAJALAEANQAEANAAAPQAAASgHAQQgGARgMAMQgNAMgRAHQgTAHgWAAQgQAAgNgDQgOgEgKgHQgHAJgEAIQgDAHAAAGQAAAJAHAFQAIAGASAAIANAAIAVAAIAVgBIAQAAQAUAAAQADQAQAEALAHQAMAIAGANQAHANAAATQAAAYgKASQgJATgSANQgRANgYAIQgYAGgbAAQgZAAgTgFgAglilQgIAEgGAIQgFAIgCAOQgDANAAATQAAATADANQACANAEAIQAGAIAJAEQAIAEANAAQANAAAIgEQAJgEAEgIQAGgJACgNQACgNAAgUQAAgSgCgNQgCgNgFgIQgFgIgIgEQgIgEgNAAQgNAAgJAEg");
	this.shape.setTransform(179.3,128.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAQB0IAAgVIAkAAIAAiRQAAgVgKgKQgKgKgSAAQgNAAgLAGQgMAFgJAMQgJAMgFATQgFASAAAYIAABaIAkAAIAAAVIh9AAIAAgVIApAAIAAi1IgpAAIAAgVIBZAAIAAAmIABAAQALgWATgMQASgMAdAAQAlAAASATQASATAAAiIAACKIAnAAIAAAVg");
	this.shape_1.setTransform(149.6,121.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhAC0IAAgVIApAAIAAi0IgpAAIAAgVIBYAAIAADJIApAAIAAAVgAgMh3QgGgDgEgEQgFgDgCgHQgDgFAAgHQAAgHADgGQADgGAEgEQAEgEAGgCQAGgDAGAAQAHAAAFADQAGABAFAFQAEAEADAGQACAFAAAIQAAAGgCAGQgDAHgEADQgFAEgGADQgFACgHAAQgGAAgGgCg");
	this.shape_2.setTransform(126.3,114.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgICNQgMgDgKgIQgIgIgEgNQgFgMAAgSIAAiPIgoAAIAAgVIAoAAIAAgzIAwgIIAAA7IBFAAIAAAVIhFAAIAACVQAAAKACAHQACAHADAEQAEAEAFACIAMABQAIAAAGgDQAHgCAFgFQAEgFAEgIIAGgSIAKACIAJAEQgHAfgQAPQgRAOgeAAQgPAAgLgEg");
	this.shape_3.setTransform(108.6,118.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhRBhQgTgSAAgjIAAiKIgnAAIAAgVIBYAAIAACnQAAAVAKAKQAKAJATAAQAMAAAMgFQALgFAJgLQAJgLAFgSQAFgSAAgZIAAhdIgnAAIAAgVIBYAAIAADKIAoAAIAAAVIhZAAIAAghIgBAAQgMAVgSAKQgRAKgbAAQgmAAgTgTg");
	this.shape_4.setTransform(83.4,121.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgzBuQgVgJgPgQQgOgRgIgUQgHgWAAgYQAAgYAIgWQAIgWAPgRQAPgQAXgKQAWgJAbgBQAcAAAWAKQAVAJAPAQQAOAQAIAWQAHAVAAAYQAAAYgIAWQgIAWgPARQgPAQgWAKQgXAKgbAAQgcAAgWgKgAgaheQgMAFgIAMQgJALgEATQgEAUAAAcQAAAcAEAUQAEASAIAMQAIALAMAFQAMAFAPAAQAPgBAMgFQAMgEAIgMQAJgLAEgTQAEgTAAgdQAAgcgEgUQgEgSgIgLQgIgMgMgFQgMgEgPgBQgPABgMAEg");
	this.shape_5.setTransform(54.3,121.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ACDDBQgYAAgNgFQgNgFgHgKQgHgLgDgPIgGgkIgIg1QgEgVgHgNQgIgNgMgFQgNgFgUAAIgzAAIAACnIA5AAIAAAVIijAAIAAgVIA2AAIAAlTIg2AAIAAgVICUAAQAqAAAeAHQAeAGARAMQATALAHARQAIAQAAAUQAAASgGAPQgFAPgLANQgLANgQAJQgSAIgWAGIAAABQATADAMAIQAMAIAIAMQAHAMAEAPIAIAhIAGAjQABAOAFAMQAFALAHAGQAHAHAOgBIAHAAIAJgBIAAAUIgKACIgLACIgLAAIgJAAgAhBgTIAkAAQAdAAATgFQAUgEAMgLQALgKAGgQQAFgPAAgWQAAgSgFgOQgEgNgKgIQgLgIgUgEQgTgEgdAAIgoAAg");
	this.shape_6.setTransform(22.2,113.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmByQgWgJgPgRQgPgRgIgWQgJgWAAgZQAAgZAJgXQAJgXAPgRQAQgRAXgKQAWgKAaAAQAUAAAQAFQAQAFAMAJQAMAIAGALQAHAMAAAMQAAAJgDAGQgDAFgFAEQgEAEgGABIgKACQgOAAgHgJQgIgIAAgMQAAgHADgIQAEgIAHgHQgJgIgMgCQgMgDgKAAQgNAAgLAEQgMADgJALQgJALgGAUQgFAVAAAhQAAAgAFATQAFAUAJALQAJALAMAEQAMAEANAAQANAAALgDQAMgEAJgIQAJgIAIgMQAHgNAEgTIALACIALAEQgJApgZAVQgZAVgnAAQgaAAgWgKg");
	this.shape_7.setTransform(157.6,79.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhAC7IAAgWIApAAIAAi8IgpAAIAAgVIBZAAIAADRIApAAIAAAWgAgMh7QgGgDgEgEQgFgFgCgFQgCgHAAgHQAAgHACgGQADgGAEgEQAEgEAGgDQAGgDAGABQAHgBAGADQAGACAFAFQAEAEADAGQACAFAAAIQAAAHgCAHQgEAFgDAFQgFAEgGADQgGACgHAAQgGAAgGgCg");
	this.shape_8.setTransform(136.6,72.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcB7IgWgDIgVgFIgRgFIgChPIATAAQACAVAEAOQAFAOAHAIQAJAJALADQAMAEAPAAQALAAALgCQAJgCAIgFQAHgEAEgIQAFgHgBgLQAAgJgDgFQgEgGgGgFQgIgFgKgEIgagJIgegLQgOgGgLgIQgLgIgHgMQgGgMgBgQQABgTAHgNQAHgOANgJQANgJAQgEQARgEARAAIASABIAVADIASAEIAQADIACBKIgSAAQgCgSgEgMQgFgMgHgIQgIgIgLgDQgLgEgNAAQgLAAgIADQgJACgHAEQgHAEgDAHQgEAHAAAJQAAAKAEAGQADAGAIAFQAIAFAMAEIAcAKIAdALQAOAFALAHQALAJAGALQAIAMgBAQQAAATgIAOQgIAOgOAJQgOAJgSAFQgSAEgSAAIgUgBg");
	this.shape_9.setTransform(117.5,79.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhKB4QgOgFgJgIQgJgIgEgMQgFgLAAgOQAAgmAlgTQAlgTBFgCIABgWIAAgTQAAgZgKgKQgLgKgUAAQgPAAgLADQgMAEgIAFQAHAGADAHQADAHAAAHQAAAMgIAHQgGAIgNAAQgGAAgFgCQgFgBgEgEQgEgEgCgFQgDgFABgHQgBgMAHgKQAFgLANgIQAMgIASgFQASgFAZAAQASAAAQAEQAPAEAKAJQAKAJAGAOQAFAPAAAWIAAASIAAAbIAAAeIgBAbIABAUQAAAIACAFQADAFAEACQAFACAHAAIASgCIAAAUIgVADIgQABQgOAAgKgDQgJgCgFgEQgGgFgCgGQgDgGgBgIIgBAAQgHALgJAHQgJAHgJAFQgJAEgKACQgKACgKAAQgRAAgMgEgAgSAIQgTAEgKAHQgKAGgEAKQgDAJAAANQAAAVAJALQAJAKAPAAQAJAAALgEQAKgDAIgIQAJgIAHgNQAFgNAAgUIAAgaQgcABgSADg");
	this.shape_10.setTransform(92.9,79.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AijDGIAAgWIA3AAIAAlfIg3AAIAAgXICjAAQAqAAAdAIQAcAHASAMQARANAJARQAHARAAAUQAAAPgFAPQgFAPgKAMQgLANgQAKQgRAJgXAFIAAABQAbAFATAIQAUAIAMAMQAMANAGAQQAFAQAAASQAAAVgIAVQgHATgTAQQgSAPgeAKQgeAKgtgBgAg3CwIA5AAQAdAAAUgDQAUgGALgJQAMgLAFgRQAGgRAAgZQgBgWgFgQQgEgQgNgLQgNgJgXgGQgWgEgkAAIgrAAgAg3gSIAgAAQAgAAAWgDQAWgEANgLQAOgJAFgRQAHgQgBgYQAAgSgDgOQgFgOgKgJQgKgJgSgFQgTgFgcABIg1AAg");
	this.shape_11.setTransform(59.4,71.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("Ag/CfIAAgLQAPgCAJgDQAHgDAEgIQAEgHgBgNIAAgHIAAi3QAAgSgJgGQgKgGgTgCIAAgQQAfgBARgJQAQgHANgPIAMAAIAAECIAAAWQABAIAEAFQADAFAIADQAHADAPACIAAALgAgmhzIgGABQARADAFAKQAEAKAAATIAACuQAAAXgDAIQgEAIgLAHQAWgBAFgKQAHgJAAgUIAAi8QAAgRgIgKQgIgJgMAAIgIABg");
	this.shape_12.setTransform(186,20.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AhNBjIAAgMIAGAAQAZAAAAgVIAAhiQAAgagfgJIAAgIIBHgXIAKAAIAAAiQARgTAJgIQAJgHANAAQALAAAIAIQAHAIAAAMQAAAMgHAJQgGAIgLAAIgKgBQgGgDgDgDIgFgDIgEgEIgEgBQgFAAgEAEIgJAJIAABqQAAAMADAEQADAGAHAAQAHACARAAIAAAMgAg+hEQAYAKAAAaIAABjQAAAIgDAEIgHAIQANgCAFgFQAGgFAAgPIAAhcQAAgUgHgIQgGgIgPAAIgFAAIgFAAgAAThAQAGABAGAEQANALAKgBQALABAGgQQgHAEgDAAQgGgBgHgEQgIgHgGAAQgFAAgKAIg");
	this.shape_13.setTransform(156.7,26.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FF0000").s().p("AgrBaQgVgLgMgXQgMgWAAgcQAAgWAHgTQAIgUANgPQANgOARgIQASgJASAAQAUAAATAJQASAIAKAOQAHALAEAMQAEAKACARIiFAAQABAVAHARQAHAQALAJQALAKALAEQANAEAMABQAcAAAXgVIAJAHQgKASgOANQgOAMgQAFQgRAGgSAAQgXAAgVgMgAhRAHQgBAmAZAZQAZAYAgAAQASAAAUgHQASgIANgPQgOAIgOAGQgNAGgUgBQggAAgWgWQgWgYAAglQAAgWAIgTQAGgSAOgUQgpAiAAA0gAAkhGQAFAKAAAUIAAAFIAQAAQAAgYgKgMQgJgNgXgEQAOAHAHALgAgdhHQgMAPgBAVIBNAAIAAgHQAAgNgFgKQgFgLgIgEQgIgGgJAAQgSAAgLAPg");
	this.shape_14.setTransform(137.9,26.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FF0000").s().p("AgXB5QgKgHgDgNQgEgNAAgSIAAh+IgYAAIAAgMIAdgWQAKgIAJgJQAJgLAGgKIAKAAIAAA6IA3AAIAAAOIg3AAIAACDQAAAPAEAIQAEAHAIAAQAIAAAHgFQAHgEAKgJIAHAIQgQARgOAJQgOAIgRAAQgRAAgJgIgAghhRIAACSQAAAdAIAOQAHANATAAQAKAAALgDQgUABgKgLQgKgJgBgYIAAipg");
	this.shape_15.setTransform(120.4,23.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF0000").s().p("AhxCZIAAgMIAQgCQAGgBADgEQADgEAAgJIAAjRQAAgRgHgJQgHgJgQgFIAAgJIBIgPIAIAAIAAAYQAQgLAOgHQAOgGASAAQARAAAQAHQAQAIANANQAMAOAIATQAHASAAAWQAAAdgOAWQgOAYgYANQgYANgdAAQgXAAgXgKIAABNQAAAJACAFQACAFAGADQAFACALAAIAKAAIAAAMgAhjiAQAMAHAFAIQAEAHAAARIAADQQAAAJgCAGQgCAFgGAEQAQgBAEgIQAEgHAAgSIAAjHQAAgVgIgJQgHgIgPAAIgFAAgAgjhwIAACCQAVAUASAAQAQAAAMgJQANgKAIgTQAHgSAAgbQAAgbgHgTQgIgSgMgKQgNgJgQAAQgSAAgVAQgAAAiHIAFAAQAcAAARAYQARAXAAArQAAAhgIAQQgIASgPAMQAPgFAKgMQALgLAFgPQAFgRAAgVQAAgYgGgTQgGgTgJgKQgKgLgKgFQgLgFgJAAQgKAAgLAFg");
	this.shape_16.setTransform(100,31.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF0000").s().p("AAbBgQgJgHgDgOQgdAbgeAAQgWAAgMgLQgNgLAAgSQABgPAHgLQAIgKAMgJQANgIAZgMIAmgWIAAghQABgPgIgIQgGgIgNAAQgMAAgGAFQgIAEAAAFIADAGQADAGAAAFQAAAJgHAIQgJAHgLAAQgLAAgHgGQgHgGAAgHQAAgMALgLQAMgLATgHQAUgHAXAAQAQAAAQAGQAPAGAJAMQAIAMABASIAABvQgBAOAIAAQAEAAAIgHIAIAJQgLALgKAGQgIAFgOAAQgOAAgIgGgAAShMQACAJABAXIAABXQgBAaAGANQAGAMAQAAQAHAAAEgBQgNgCgFgJQgGgJAAgSIAAhlQABgXgHgJQgHgJgQgBQAJAEADAIgAhJAlQgKALAAAOQAAAOAMAJQALAJAOAAQAOAAAIgDQgVAAgMgIQgMgIAAgQQAAgLAGgKQAGgKALgNQgSALgJALgAgZASQgMANAAASQABANAGAGQAHAHAJAAQAOAAANgOIAAhHQgbAPgLANgAhFhIQgIAIAAAKQgBAFAFAEQAEADAGAAQAMAAAFgGQgHABgEgEQgFgEAAgFQAAgHAEgFQAEgGAJgKQgPAIgJAIg");
	this.shape_17.setTransform(77.9,26.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FF0000").s().p("AAPCfIAAgMIANgBQAEgBAEgCQAEgDABgFQACgFAAgIIAAhoQAAgTgJgKQgKgKgNAAQgVAAgeAbIAAB3QAAAMAGAFQAGAEASABIAAAMIhtAAIAAgMQAOAAAHgEQAHgDAAgMIAAjYQAAgegfgIIAAgJIBJgXIAJAAIAACWQAQgOATgIQARgIATAAQAUAAAOAHQAOAHAIAOQAHANAAATIAABdIABASQABAGAFAEQAFAEAMAAIAFAAIAAAMgAAyAKIAABzQAAAIgCAFIgGAJQAOgBAFgGQAEgHAAgPIAAheQAAgRgCgJQgDgKgIgGQgIgGgSgBQAYAJAAAagAhvh/QAQAGAGAJQAFAJAAAPIAADSQAAAKgBAFQgBAEgEAFIAGAAQAFAAAFgGQAFgGAAgKIAAjVQAAgQgEgIQgEgHgHgFQgHgEgIAAIgMACg");
	this.shape_18.setTransform(54.5,20.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FF0000").s().p("Ag2CWQgegMgVgWQgWgXgMgdQgLgeAAghQAAgiAMgfQANgeAWgWQAWgWAegMQAdgMAgAAQANAAAKACQALACAPAEIAUAFIAMABQARAAAMgMIASAAIAABiIgOAAQgKgWgMgQQgMgRgOgLQgNgLgPgFQgPgGgRAAQgWAAgTALQgTAKgNATQgNATgHAcQgIAcAAAfQAAArAPAiQAOAiAbATQAaASAgAAQAVAAATgGQATgHASgOQARgOAPgUIANAHQgZAkgjASQgjATgtAAQgjAAgegNgAhah3QgNALgJANQgKANgHAPQgHAPgDASQgEARAAARQAAAnAQAiQARAiAgAWQAhAWAtAFQgegIgYgPQgYgPgRgVQgRgVgIgZQgJgYAAgbQAAgVAHgZQAIgYANgTQAPgWAPgNQAQgNAVgNQgiANgWASgABgh5IAPARIgBgmQgKAFgMAAIgKgBQALAIAHAJg");
	this.shape_19.setTransform(25.5,20.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#000000").ss(1,1,1).p("APlgEIABAJI/LAAIAAgJ");
	this.shape_20.setTransform(99.8,149.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FF0000").s().p("AvkH1IgBAAIAAvRQPcgwPvAwIAAPRg");
	this.shape_21.setTransform(99.8,98.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0066FF").s().p("AvkH1IgBAAIAAvRQPcgwPvAwIAAPRg");
	this.shape_22.setTransform(99.8,98.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_22},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(99.1,67.5,201.5,196.9);
// library properties:
lib.properties = {
	width: 200,
	height: 150,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;